# | \ | (_) ___| | _____ _ __| |_ 
# |  \| | |/ _ \ |/ / _ \ '__| __|
# | |\  | |  __/   <  __/ |  | |_ 
# |_| \_|_|\___|_|\_\___|_|   \__|

JoinTitle: "" #Title when player joins. {player} and {world} can be used. Only visible for the player self.
JoinSubtitle: "" #Subtitle when player joins. {player} and {world} can be used. Only visible for the player self.
WorldTitle: "" #Title when player goes to another world. {player} and {world} can be used. Only visible for the player self.
WorldSubtitle: "" #Subtitle when player goes to another world. {player} and {world} can be used. Only visible for the player self.
Fadein: -1 #The fade-in time in seconds. Set to -1 to use client default.
Duration: -1 #Duration of Title in seconds. Set to -1 to use client default.
Fadeout: -1 #The fade-out time in seconds. Set to -1 to use client default.